name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [auto]
        include:
        - os: ubuntu-latest
          arch: aarch64

    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'

    - name: Set up QEMU
      if: ${{ matrix.arch == 'aarch64' }}
      uses: docker/setup-qemu-action@v1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      if: startsWith(matrix.os,'windows')

    - name: Add Windows SDK
      shell: cmd
      if: startsWith(matrix.os,'windows')
      run: |
        choco install windows-sdk-8.1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Build wheels
      env:
        CIBW_BUILD: "cp3?-*"
        CIBW_SKIP: "*-win32 *-manylinux_i686 cp35-* *-musllinux*"
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_MANYLINUX_X86_64_IMAGE: "dockcross/manylinux2014-x64"
        CIBW_TEST_REQUIRES: "pytest"
        CIBW_TEST_COMMAND: "pytest {project}/tests"
      run: |
        python -m pip install cibuildwheel==2.3.1
        python -m cibuildwheel --output-dir wheelhouse

    - name: Build source
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        python setup.py sdist --dist-dir=wheelhouse

    - name: Release to pypi
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        python -m pip install --upgrade twine
        twine upload wheelhouse/*

    - name: Upload artifacts to github
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
